#![allow(rustdoc::broken_intra_doc_links)]
#![doc = include_str!("../README.md")]

pub mod ansi;
pub mod error;
pub mod render;
pub mod source;
pub mod line_index;
pub mod marks;
pub mod viewport;
pub mod input;
pub mod terminal;
pub mod app;
pub mod cli;
pub mod format;
pub mod file_set;
pub mod filter;
pub mod prompt;
pub mod grep;
pub mod hex;
pub mod prettify;
pub mod batch;
pub mod shell;
pub mod preprocess;
pub mod keys;
pub mod style_spec;
pub mod open;
pub mod overlay;
pub mod tags;
pub mod keymap;
